language: node_js
node_js:
- 8
branches:
  only:
  - master
cache:
  yarn: true
  directories:
  - "./node_modules"
env:
  global:
  - secure: "lEujSteUXXVvOpu+GtwfycOA35lPLD1VtyngI8rzwnNS42sOggOJu6S9GZxLHJKhIAb8c9Wtdtke0sHMdsinzOggYx7Wrn7pDaW7f7Im/g8GlPpE8Bj1Bizu3rjbIK3cPYTw2Yu2IGLssxcz1dClaAnoU0qVpTVKpw3XMeIvV0+2t3dyKTmsca+WxJxhZZ/e/LHdlGFRh3vxOByfingtgO4AmiwKEeN6ZWhtTmyMe6MyXOCFutmf84YZK7makPnwD84+u56PjcmZekByW9MK6IE6qBx/+dxGSqENh6HpKw9DdGi6bcPFU0elgoEVCPcHzgU87vUYnddsf3om7Ej5FTUNHSbvDhjlDBXx5b6fCmDMcQLaQLUsOmdTrDK2IGxQfuHAMz9n4pSpEy8h0T3nI4YvJG3/bCCn1Iijk+Zs2A5JZ68N4K+3zwVzTZjkEr76S5Bv0HD1xrW/uCz7fqZeEkqyRjIcFQMyjKyYsM8vfTSOpxSWK0DbE+1yIeTs5JcFqM2gt6U7jtBP1cUpiQImGm1QvJx3qjyh5ZCavHsglNrlKcH6IqUPrFEXWNWGgALQMYh7eTbz6gD0Oc/yusFvd9Ch52NxFpfKsg8v0+EM9sSOz1GaqhqiDRDLWEXzG8r4MU1QEAuK7/7WzVOEqCwAQLJaM18mg1QyNT8w7AvGRls="
  - secure: "Jsg6Ike7kb1J1nrmC8rC41zDCc46O9evRciD6K7CCRWkOMbxyCLOG5G2phugr6C0l0OMbvd7jLCfIn1HIfyBiMmm0Gb/+vUlzSUvRapiNGC0ylZvBNVJwhiFAlCMDjAN/HDYGdZGaM5WEadu75K7HBTobP82sMW+SelO7y44NgoXE1aVjGdnHsFZcXM/sVrMvcrmJYPsFN9QTEwFXW2a48EE0S8T76Hh1K0wQFwhI8gkebsIUaS4zEzt05NfYFN+pkfW2rfm43SR/+CeQmMyoEGLBgSVYCc8lsxQNGCFWhppdKTgzpcixzpzCBTr8D6Ve8JXyxsVNLH7eDBDKuHTfgMBFfha8hJVnNyZQi6E3cF0FszdMRKPofFnK2rRI27TMGmdMdOru5poVnwa1b8V/FEU7+lSzATMu1Jjjcu0TB4yCCd9d1dEZ/eU/n1DqIoFtQz/yPCUNKlIO/35TJAPJUjCvI3k/hp9NlIb8IzJuGFEfHz7+DEeiQJ9SCEW7GntcF1I5a4j9iq6449HBPZtlrrW2coKMidg2S8sz9+3FwNRhV4BfNSV9DzHVFFN2As5VwQCh0uvrAjMrWTjpBWL1lAx9oE28KAqojp9tvQOWDVaHwRFJ8gTsQOA0COpu66zAZ+1tsrkfCigYK+MZz01qG6tjHbv0HBKtNzP8/fwIY0="
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
script:
- make travis
after_script:
- tc-builder slack-notify
