language: node_js
node_js:
- 8
branches:
  only:
  - master
cache:
  yarn: true
  directories:
  - "./node_modules"
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
script:
- make travis
after_script:
- tc-builder slack-notify
env:
  global:
  - secure: hik4JYul34M/ERfrDZplE7kj7JTS/uCsXOCglc1FURw0t7clSVsEZ7jpzKaFbDUbRdkGcdwg/o67cksMjYp3CjfIlf2uTzRbomiPxjCa4h7DYS5KNgC8bQXV3Ce+LNukXizQCjGoD8ynSPTpJ5N7OEjnaay87dO5ggoghYxRJUg4lhtTPK60b/R665wS3HOR8JuKQE/QU8IvS9ERxJMd4WC5/pkPi+op+PR9ojkJuzkj6z6/RQ1RjFVbsRJZ40kxFMDJHf1K2vu+sJM5+uHKNQ9Ql5x+ouEQGoCQjekUhIJPLJK2uVUgVJUibeGHpTYyez6oNXXuy4II5XfFDLV0VGyHXQcchIm4XA4rCEeUAUhucgRTO9pEOH/RI8au/eGS+UibntrUJ1QzwIN8om1ArV0ktCjz28mFDKKlPUisp3os3Dlz52jjvwvoUZ2KCDyAmuSP2EkxDO4GtuMzLGbgJ6bboAACTaM4zYeWbxeqy2sTWnlkhcx9rLlN69jN8UyxiLuZ/XaOu1wSttwTwcrbDVqrFzDUmiBVUwQJZQscC9HUIsjrUfaVhYWmOF5+SGLMQ/HOMjqsxCAszsYxlvqZXBAb6r3XvNGVpGL2pPOej0+s6LRg5OtldFz9qOe6pTWlJBuWkCrwfTVApaNwvn8FjVSF5436dKF9A+uGiZWAMNY=
  - secure: lmip5lOsYhammK4Unx8Vl1FEZXx6n11Ohx0+rgnTdCJwgOVtpb9r/vU/+ahIQoccqgD6fEmz1Pg6fgukgteAVNMzBhuCbFrYO5qPZPFz7rfbks/Z5KjErxmrPztSrZAZSu9avpE2a5lIQ2bEzqIDQjZ3KKBLayz5VGKJdMe8lLYzPPFVjemyI5yU+cy4E9TI0pZFAjlpLxCc2/u8GglDMYt67kmxIKQmOdB5HX4V06w+lyJmkQWXKFRF7Bu2yf4UbvsOLEq0O3QCjlTp+3zRHZOwhFY+Dzd3MWoaK+eOsBOLdsSzWTsNxfTCm+LEjg4b2TaxMOjf4cyCfRdGNjJ4x++NzCW+Rm9pQzlNfcG1/YrW9W3qqKb76Iiomo0hTSIHWTpjexwM1mJ8eot1FIHs7HZW2VeLkAHf0q60Q0/plUPZfiJUFrqf2EKHJc+FdAen6FC67bmYpihCHCpQLOGJA/J8b532FGlsUUabLpt1VepRAZPc04tf8j4nzloQDTSTVHvnW5Hl5rLIBhexIzfi6sXUTMQZY1Af8g+DnBcfuSQAYK6oSeWqP24KT9r0EQF+r7gJPVMSxMxBv/8sBS4DJtkMWxcGsrSdeCthdAMfTWFW0fiqLVhDtF0z47KTYYNpR2DEbad4WwIa3S7atWbaKOA4q97lDeIUjY++1JktROk=
