language: node_js
node_js:
  - 8
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - "./node_modules"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - make build
  - ts-node ./scripts/builder.ts

after_failure:
  - echo $TRAVIS_TEST_RESULT

after_success:
  - echo $TRAVIS_TEST_RESULT

after_script:
  - echo $TRAVIS_TEST_RESULT
  - ls -al
  - env
