language: node_js
node_js:
- 8
branches:
  only:
  - master
cache: yarn
env:
  global:
  - secure: "Y4ebMmrZNw2ePSWig1BR6zlu6m65bFsbaspHHhlMxrQOfwLct7MFGQ58oVr8VGy5+K19ssm+NUjOJH8q0LyqOwg4EfLNNtfQLD7MifvpLglES10Q1MTtGNcjEx0/HOep4LiiDLuq8yYj5WFIXZ9A8Hc64KTUQBpEvTwFZkS521srGESGDt/+Kw3+KfBiYxlwFSPJHCK3nU3ucNIU7QKC5NXiq0O9YI70G3pBBhPSvesCtB/UdvhhzRZTBtrYS2mZZHJM+83hf5CQErVatv1JO6Sx9wOLJ+dkF9oZK53tjdeOp2nEkGyCF1qQ1UVObM855Cytj/piseJw/lryZ0ImjLW7tvCMtX3ElfR+vlMDfT6fCzY6+NzXPdAIR7jKB7VMVevm+OGCWRLfU8nJ5wGf5odiCU/6sQ1qlmtsHqX9QcQqfOrXlf71fZJKbYVRrASVMWoeJx+CNDehNWkMAD6DnI/Jkt+C7FYA2pu4ntYq+jeAnV+2nTM7uIpgD1FTTXCdt1+ilukUQkJsW8bqvm3z32jqaGQI4m8s1mkseSWBm6jF5/3kJqeg7IfIFwRUhdoNXRtyyIdbIC0OrwDeI3k/ltK3YIkkOvYUaqQ/V99LuGldAc+TLrQVM3oXEIYCoCpPZMZiEFnCW7x+ATREYddqY51M5KSV/L7UWc2mtcMRGZs="
  - secure: "pRjzT439gAYsS2VgOpFZhCr+VWjlW38AxLVDX9z6mUp8WMQP00sm2FH1Exj2G04sR2LO3E6h4VZTFEnwbGsIT9LH8T2esMAX2MdJT3FwqdK+kmfRwEKgRa5JK1ZzT0v71TGrDdTPVVPSuxgxmBlM0btyNehMXrhlBBRpfUA4BDd/JpP9BISm8RSPieCQEkYHOAQn00MyAthmOmc38q/suHGJsM+zzDmmhxCgBcMvy+wBoQOiXghmp1bQWlYJWSaF8yYYVh5acxAGmSYo1qXBZ05lMKXXXtyrxjFI0q6u9nywL4nKpjmwRsBJ3dFcB7CjOHZ6BxxHgZBq5dCZtvKOAfX9U1OD1DQDvMOWC7333F/l1Rfju52kVA3l4RJUSi/9C6WpvIfMzgBwqMV2MTmQN6ihzOzOwL5xQDNxnhh5xNhdhfE616l+d6cM3dSRjopGCMCh3IQ9STyHo7EynDWs8IGDYSLo4J6G3irIdBhVFRbr1ZEcRysuI7Tl8TU5+6HhDL4u6gHYPugLSdq2uI5Mwg+uGQ4ydjQl/DlbE2318R6q0vy6ss9LMVapEl321EVemxBWnIbVEU0sWX7W3SMwB3GNwQzc1HD/nKF9rw/YmgbEh/HlTgnjWVXasRX05HIILYvpZHbI3NzEbx31k+mhw8E6mHHPlbt1b2RoxezfJOE="
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn install
script:
- make travis
after_script:
- tc-builder slack-notify
