language: node_js
node_js:
- 8
cache:
  yarn: true
  directories:
  - "./node_modules"
script:
- env
- echo "$GITHUB_TOKEN"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
