language: node_js
node_js:
- 8
branches:
  only:
  - master
cache:
  yarn: true
  directories:
  - "./node_modules"
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
script:
- make travis
after_script:
- tc-builder slack-notify
env:
  global:
    - secure: 'CUjBpDE+SfCmg5xDdd/T4+psegn+XWyJxXgqisgwwdGpjvV+AxnafRMh/ygUzILIyrmDGizgdv4tJPA7IdpjLBnJXhd7kWisw9xZtccetaVS5Vx1DPD1qh+VTkBb5kKtwLTvCAW9HdGLVRMD1ADKfaJDxgmUVwKm3tCLK5lxJXiZDZjESvit2roxOJ4muavKUsTeY5PtrjiwVlCoCMJBOPnsGmMhpLuynnnqqNxTo5YapHMQghSHqGfMZyKrTDkqQKVTHyO8expE1j4AP7j6YPjgv8rQLkdVWAdKEnpa+sPVBTBiy6DoM7p6rOMV5hS289Om9QArHX931mYzwdHPkf8HMNgSWDzz8Zwz8hu5bsFaCnRph58ehvABabaLSi+OdjBomWzweJyx+Oz3Ma2ncQ1EyZoeFHLf4FnZVrRtIHVFnIDM1m5S3+w7bhQytnejPLSeResN4M/JqIFzy0c1ilBhKBQR4AlC9Hg6IntGhz7U9TB2Hp64ZcS/zqiLspSuZrA1UmrEF4TAsVdZ8ktcU700DwIKR+QjfkzD2TmovDIHCrt8nWEEzhum6GdmP0MHx33Coz7niGdkhboPmfQhNvu37+CXp/25I6ckx+0FOZ+gNGEbn4JBpqJ/PHTS03pQ1HatCDY1WARjctrOmhFSQv1jugmoyO1JotSypZK1Y10='
    - secure: 'zJOcuCzUIiV4fGbF7nYbqfiFN5fjzFmqGW1Od5zEVhk31Plym+0RrcgiYy6m0FvcUqeNTRIG+2zR21aRg+qOHE67DXnzL3p6cB7U12ovLCZVqcP2d1/Q77vAaj9UKiAmvvdNHoGT/L58sYo76qUbKGer5X8ow33EfQuJFQuw0j2sXgqRZ8R7iNEwH8ah+uGs85SxKHtfxludfKVOUA05lW5zsXOHUT0uniFz3UIdpTM7NIS1VE8LRDYhnw0V+EC06XcLFJO4PXw05keWLt6Pf8kkbHGUN2BQFrPY0Ps/Q3TUkGL0lfyrB5yEsC8ZV/1IqSORY5NZcWyVMsZqZK6ElVjplEEpfJKn5grMxuWtQAo8PR6pT9my5K1DrEpWGjLbTi9uiYquT4LF7vJDGXHslm0Nh+YZdMjAHNs8nnMxS9HeyZHdDpDCYxOwx05B7b2SzwifN+GxTv6M9w3DGuNRhnafEINSYuOPs8oB/UVH2yIlkiOrkVhqOiVN/yMXyNjV+wKMJmz9+WEIUaGgT0VsepUiUdt7/rgKY4f+2Rcx8FdHTyEMC8WoKZuAVnoO4AlbtbioKMJJOC9zziz7SfGHVAwxSBsnHv48P1wpTDQxKowPIZErwfS9rF3klEZJ2Pgd79Mp7LSoh40d7T/4btCCSo6R5uKycWRTDi503GBpMI8='
