language: node_js
node_js:
- 8
branches:
  only:
  - master
cache:
  yarn: true
  directories:
  - "./node_modules"
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
script:
- make travis
after_script:
- tc-builder slack-notify
env:
  global:
    - secure: "FCFmaORkQ7wfgGTxklc1lcp3IEu72NLzy8ZggszjzWcosSRW4yPD33OibgN82H/8FswXKKLUI0V7pAn7mV/e2D6btVHb7KlQ7isBkeBNLVA4iSnrUMqczNH9zLPtkpjeHcmf0t0mJ11twHH+HZnSTVA94qPQ5Xxgh9i91ppGMtA0UASPzkxFZr7XKcEF/YqOMi+zHNK930lULV8SnVQFxL4uJ/BHW06MMqLxm0UhJMau7JTARO+pilCTcCwYQDKjs3nnKXiDe2iF42545kGZl5CnMqsNQibze7oZVFsXt/9XXXlBRTNHjdqkYbF+rBCCqvu5s8EGMHGQ7Vad3f7h+88Oo2lPGid7cpA86UbeHOPvVx6Lpu2JSaLOpE/7pNQjF9pFAnD5h0TLsveSEsnWpIxP0uz7k1sKd4OGRtElJelJdXrbKlPgAJjcDvwR3wXbQHLaRS1AyOKXVL3TV+5oQhd04LObu2erp4zglaEFHsv3k2FbGKPrRtTplW1+iygHtUUpR7iV193X0x8H3TpLqHy9VGJATkgYS8Ntwyjwl8zAztqCjdJjibPNmW2R4swLa2S4dp10Xf+mNH4XrqPZYrxWTWBeb0A3ADHMlnCv2Xg0uwHl9diQULzLtiVi5oMsPSskKIZmjFKYCDbmUyb+//0xhMG4jwLot+GG2jHXFbs="
    - secure: "ovAc+QGexhqmeIJs4M6HEpUr6Qokihrxk1JkrUUsqnByRu9EoJ6PD9+cDxtGQ1PccMSAqb3+M8Yf910ACJ6GnZcEX7tAlJNXJ6nIgeVkwn+maYchhYoj1pOmAsWsAiV9pRwdsh+K38tFXQcjST0eoG15qr1bDIf3ffyJiz+lDPQ3tm61exihtbrW4IH10jkM8hLAJ/wXBZNyESGQg4lnyBi4aAVGYzsOUKCnEZ9g9bz/WekSEUEO6tOk6AL8lSTO4UNCcH/N7vx/Ui+ehHU7myQmo9888v2MN1p9cyoxxBe2EIOsC0JQrSgjGi14Sa5XrswAwjVa9aWKRcCJvI/JKicVi4nHgCODOvrZgbphRQ4xT76tXnXelbAZ/cuWHG6R14tcAnFzKwnkqxZ1nOklOCyzWx2uUGjEL8/OosOVyBZiIC9SUxeJOD+QPK+S7Q36VSxFf7CeyY+c0SIqaiKqChTZT3ptEc3YYL7WHi/5+nQkTGjDyv5YHkfhkfC+4Ixs6lRxtw56aLD90YULCMoo2KCSDlw0PaPqlVZzAd5RuK0AnB6YFGXYs5/0kH8F1p2wPdgwEEUow+IEVbs/4T9fpy6zSdUiQ7Oc279m2vwmAeoh8cKGUffpJsl1z9e+7XFFJmv0rlV0tp7LjxuJrZLVWaBiLj/9OnE+mQyASQbMhNQ="
