language: node_js
node_js:
- 8
branches:
  only:
  - master
cache:
  yarn: true
  directories:
  - "./node_modules"
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
script:
- make travis
after_script:
- tc-builder slack-notify
env:
  global:
  - secure: Gxl/gmtVC7FNOs/UxelrZnLX/Zf1eVRfFGJGEsl3jYsZ7ZJDN2dID1jnFMeGueTRKJu1yeKwoWf8FUsT1bFaRXggED3pcd6gJnWApCc4H0rsrsgT1DuY1nrU8sBN0yaywpSCYKCmF8PKw8m7iMQkt0cB7dri5ITK/FnWq9gkvrD0KSFM1+RYGseOZAmVwMymdYL062s5/6dbT4PCOmN7L1Nr/mFuo8De1X88DHBKi+p2jfryYSJ2uxMnc9qCto6FydGsiYCH0FhDAorejUD4E0PmXcSGceCnF6bIl4zENRWS8cc1mVTsAL1Zapgn7vNPClDCyLJn5+1D9ckhJvXg/wMVzdCIC7mTA4PoMyaAnahXgXuNtUUKz2udLgcpJ8Qw2OS9uEa6Z+wYmNcxG8CxmS0ibUssN/iQNIN+uieie76sYTIJHGzmurtGLLadc6HR/hjrYw9eSv3a+MjuKeiK4fDdraMHqT3Y8s2+tioHlwt3gLolkjNu060M/JWVvVCRMsWSqv0ZuIfNeuisbmAHoAQqhQfrjIVa+ArOTM0r0cSsxuLFOiXdgLvMah8GURZ0mjv83CF55b1cyJDCNbQFxDaOC2clmfoYJaOri8thzPcP/YulfJvRjdzwUoKtKbQ/brkQp7LBLsSiGMQbd1EOSAF1NptkZGTFgDS8u3cJBBs=
  - secure: Hq5dQLZcvChTFbv8RgTWRg6MGfRaHNs3z2SinCbUEPXoA6U+sTlupVKyQpBbFCWPJ4wKA2FxvcXCzJrCQGx6X2TUqMEV6Nkmo7L2vxbWff5f4hIiRhQQvT/Xcexs/qQniW0m22rco1jRfLJIjCuarhZajsXlh6P5j/PuyW7js6AJSNHY6wUsVpU7GYMKbfKnzT2ncrIx/JphdArea0xTQ49TZPfRWeQocpEN18KU84chF3616jNntB2Yiy7OLooEjqfRuNGo+lm+b/tytDInE3pmgyi08THYloSO6haBCIFVqFQViHqWM/2PL1hRbwe+3aqVO0XT5FxQlz72GpC0OpH3F9OzuvEO1KkaRaKR12BH5gEPjZQIGub60cTiMPAjKXlcujMo6+GC0Ta7Ybfe2n0xP638ditPG9lLBh6JMBUQyVPVnJYKX2TC8HHrb2Ufn1hQ2d0U4EPpTn6PWFwEMmIsAuYdH8QHzw/kTuRjvtfRqXOxjwXgg3+LCUrLRMIAiORCgebL/24QcYI6adFhmzZlo9HGL0kabubyB6Ao6mv4wIU/BTchWyv6oypi+SDtEOsjfOgRdFYmidHznub7jEO58Qbmv+kIf6kdJTYuHzeelgdQKOhKvec7RMiEV5rLjesifnmVXlaptGBz00nLDV1ZQtV4oWIoa/lVvvF+RiI=
